# https://www.tutorialworks.com/kubernetes-deployment-spec-examples/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: wkx-practice
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          env:
            - name: wangkaixuan
              value: hello
            
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: wkx-practice
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31378